import { ThemeProvider } from "@/providers/theme";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactScan } from "./react-scan";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
};

const quicksand = localFont({
  src: "../../public/static/assets/fonts/Quicksand.woff2",
  variable: "--font-quicksand",
  display: "swap",
});

export default function RootLayout({ children }: Readonly<React.PropsWithChildren>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${quicksand.variable} antialiased`}>
        <ReactScan />
        <ThemeProvider attribute="data-theme" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
